name: Deploy to Dev
on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

env:
  ENVIRONMENT: dev

jobs:
  # Load env vars and other preliminary stuff
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: env.ENVIRONMENT == 'prod' && github.ref != 'refs/heads/master'
        run: |
          echo "This workflow can only be used on the master branch."
          exit 1
      # Checkout repo
      - uses: actions/checkout@v2
      # Checkout private cfacorp actions lib
      - name: Run read-yaml config
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: 'config.yaml'          # File to read from
          key-path: '${{ env.ENVIRONMENT }}'
      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
      - name: Get Secrets by Name and by ARN
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
        secret-ids: |
            test/secret
            parse-json-secrets: true
    
      - name: Run liquibse
        run: |
          
