name: Deploy to Dev
on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

env:
  ENVIRONMENT: dev

jobs:
    init:
      name: Init
      runs-on: ubuntu-latest
      outputs:
        services: ${{ steps.generate-matrix.outputs.services }}
      steps:
        - name: Run read-yaml config
          id: yaml-data
          uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
          with:
            file: './config.yaml'          # File to read from
            key-path: '[ "${{ env.ENVIRONMENT }}" ]'
        # outputs:
        #   db_name: ${{ fromJson(steps.yaml-data.outputs.data)[0].databases.*.name }}
          #db_name: [1,2]
        - name: Generate Matrix
          id: generate-matrix
          run: |
            # SERVICES='${{ toJSON(github.event.client_payload.services) }}'
            # echo ::set-output name=services::${SERVICES}
            SERVICES='${{ toJSON(fromJson(steps.yaml-data.outputs.data).*.name) }}'
            echo ::set-output name=services::${SERVICES}
    my_matrix:
      runs-on: ubuntu-latest
      needs:
        - Init
      strategy:
        matrix:
          service: ${{ fromJSON(needs.say_hello.outputs.services) }}
        max-parallel: 1
      steps:
        - name: Matrix => (${{ matrix.service }} )
          run: |
            echo ${{ matrix.service }}